version: '3.8'
services:
  simple-nestjs-app-db:
    container_name: simple-nestjs-app-db
    image: postgres:16.2
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
